ALTER TABLE packages ADD tags TEXT[] NOT NULL DEFAULT '{}';

CREATE TABLE IF NOT EXISTS gallery_images (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    ordering INT NOT NULL DEFAULT -1,
    s3_id TEXT NOT NULL,
    package INTEGER NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
