DROP TABLE IF EXISTS user_tokens;
DROP TABLE IF EXISTS package_authors;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS package_relations;
DROP TABLE IF EXISTS package_version_refs;
DROP TRIGGER IF EXISTS update_packages_updated_at ON packages;
DROP TRIGGER IF EXISTS update_package_versions_updated_at ON package_versions;
DROP FUNCTION IF EXISTS update_updated_at_column;
DROP TABLE IF EXISTS package_versions;
DROP TABLE IF EXISTS packages;
